name: cafeshop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # A powerful Http client for Dart, which supports Interceptors, Global
  # configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^3.0.10


  # With this plugin, your Flutter app can receive and process push notifications
  # as well as data messages on Android and iOS.
  firebase_messaging: ^6.0.16
  
  # A Flutter plugin to use the Firebase Remote Config API.
  firebase_remote_config: ^0.3.1+1
  
  # A Flutter plugin to use the Firebase Crashlytics Service.
  firebase_crashlytics: ^0.1.4+1

  # Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with live synchronization
  # and offline support on Android and iOS.
  cloud_firestore: ^0.13.7

  # A set of utilities that allow you to easily pass a data Model from a parent Widget down
  # to it's descendants. In addition, it also rebuilds all of the children that use the model when the model is updated.
  scoped_model: ^1.0.1

  # Wraps platform-specific persistent storage for simple data 
  # (NSUserDefaults on iOS and macOS, SharedPreferences on Android, etc.).
  shared_preferences: ^0.5.8

  # This Flutter plugin provides an API for querying information about an application package.
  package_info: ^0.4.1

  # Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) 
  # API for generic location (GPS etc.) functions.
  geolocator: ^5.3.2+2

  # Flutter plugin providing detailed information about the device (make, model, etc.), 
  # and Android or iOS version the app is running on.
  device_info: ^0.4.2+4

  # A cross platform plugin for displaying and scheduling local notifications for 
  # Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: ^1.4.4+2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
